name: love_calculator
description: A new Flutter project.

publish_to: 'none'

version: 1.1.1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_dotenv: ^5.0.2
  get_it: ^7.2.0
  http: ^0.13.5
  path_provider: ^2.0.11
  percent_indicator: ^4.2.2
  screenshot: ^1.3.0
  share_plus: ^6.3.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
